#CI pipeline

name: CI Pipeline
on:
  push:
    branches:
    - 'main'
  pull_request:
    branches: 
    - 'main'
jobs:
  training-testing:
    name: Training and Testing
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      
     
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
            python-version: 3.8
      - name: Install dependencies
        run: |
            pip install --upgrade pip
            pip3 install rasa==2.8.0
            pip install SQLAlchemy==1.3.22
            pip install sanic-jwt==1.6.0
            pip3 install rasa[spacy]
            python -m spacy download en_core_web_sm

      - name: Testing nlu model with cross validation cv=5
        run: |
          rasa test nlu --nlu data/nlu --cross-validation --folds 5


      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
            commit_message: Updated Results
            

      # - name: Upload Cross Validation Results
      #   if: github.event_name == 'push'
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: cross-validation-result
      #     path: results


      # - name: Upload model
      #   if: github.event_name == 'push' && (startsWith(github.event.ref, 'refs/tags') || github.ref == 'refs/heads/main')
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: model
      #     path: models
